### ISSUE TITLE
Seperating the data values into chunks?

### ISSUE THREAD

**Issue by meraklimaymun** [AhmedAzizKhelifi/coronavirusTrackYourCountry#2]
Python noob here. Is it possible to do this by filling certain variables instead of combining all values into a string and serving the user as a notification?

I was thinking of making the numbers appear on a Raspberry Pi 7" touchscreen and update regularly. I'll use Tkinter to program the GUI and insert the numbers on certain textboxes. But I can't access the data individually since you put them all in an array. 

Can you make a version where the numbers are stored in varilables like "total_cases, new_cases, total_deaths, new_deaths, total_recovered, new_recovered" etc...

Thank you in advance Ahmed Aziz

**Comment by ahmedazizkhelifi** [comment]
You actually can extract those data from the list. 
The data list is actually:

|element| Total infected | New Case | Total Deaths | New Deaths | Recovred | Active Case | Serious Critical |
|-----|----------------|----------|--------------|------------|----------|-------------|------------------|
|index| 0              | 1        | 2            | 3          | 4        | 5           | 6                |

You can get those data using their index, or if you insist to create separated variables you can do it for example:
```
total_cases = data[0]
new_cases = data[1]
total_deaths = data[2]
....
```
